import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <p>Logo</p>
          <div>
            <p>Link 1</p>
            <p>Link 2</p>
            <p>Link 3</p>
            <button>Button</button>
          </div>
        </nav>
        <main>{children}</main>
        <footer>
          <p>Descriptive text for the footer.</p>
          <div>
            {/* Social links removed as per request */}
          </div>
        </footer>
      </body>
    </html>
  );
} 